config/routes.rb
Rails.application.routes.draw do
  resources :posts
  resources :forms
  resources :customers
  scope '/api' do
    scope 'forms' do
      get '/' => 'api_forms#index'
      scope ':id' do
        get '/' => 'api_forms#show'
        post '/' => 'api_forms#create'
      end
    end
  end

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  post '/users' => 'users#create'

  get '/start' => 'start#index'

  root 'start#index'

end

app/controllers/forms_controller.rb
class FormsController < ApplicationController
  before_filter :authorize
  before_action :set_form, only: [:show, :edit, :update, :destroy]

  # GET /forms
  # GET /forms.json
  def index
    @forms = Form.all
  end

  # GET /forms/1
  # GET /forms/1.json
  def show
  end

  # GET /forms/new
  def new
    @form = Form.new
  end

  # GET /forms/1/edit
  def edit
  end

  # POST /forms
  # POST /forms.json
  def create
    @form = Form.new(form_params)

    respond_to do |format|
      if @form.save
        format.html { redirect_to @form, notice: 'Form was successfully created.' }
        format.json { render :show, status: :created, location: @form }
      else
        format.html { render :new }
        format.json { render json: @form.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /forms/1
  # PATCH/PUT /forms/1.json
  def update
    respond_to do |format|
      if @form.update(form_params)
        format.html { redirect_to @form, notice: 'Form was successfully updated.' }
        format.json { render :show, status: :ok, location: @form }
      else
        format.html { render :edit }
        format.json { render json: @form.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /forms/1
  # DELETE /forms/1.json
  def destroy
    @form.destroy
    respond_to do |format|
      format.html { redirect_to forms_url, notice: 'Form was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_form
      @form = Form.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def form_params
      params.require(:form).permit(:name, :receiver, :customer_id)
    end
end

app/helpers/forms_helper.rb
module FormsHelper
end

app/views/forms/_form.html.haml
= form_for(@form) do |f|
  - if @form.errors.any?
    #error_explanation
      %h2
        = pluralize(@form.errors.count, "error")
        prohibited this form from being saved:
      %ul
        - @form.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :name
    %br/
    = f.text_field :name
  .field
    = f.label :receiver
    %br/
    = f.text_field :receiver
  .field
    = f.select :customer_id, options_from_collection_for_select(Customer.all, :id, :name)
  .actions
    = f.submit

app/views/forms/edit.html.haml
%h1 Editing Form
= render 'form'
= link_to 'Show', @form
|
= link_to 'Back', forms_path

app/views/forms/index.html.haml
%p#notice= notice
%h3 Listing Forms
%table.table
  %thead
    %tr
      %th Name
      %th Receiver
      %th Customer
      %th{:colspan => "3"}
  %tbody
    - @forms.each do |form|
      %tr
        %td= form.name
        %td= form.receiver
        %td= form.customer.name
        %td= link_to 'Show', form
        %td= link_to 'Edit', edit_form_path(form)
        %td= link_to 'Destroy', form, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Form', new_form_path, :class => "btn btn-success"

app/views/forms/new.html.haml
%h1 New Form
= render 'form'
= link_to 'Back', forms_path

app/views/forms/show.html.haml
%p#notice= notice
%p
  %strong Name:
  = @form.name
%p
  %strong Receiver:
  = @form.receiver
%p
  %strong Customer:
  = @form.customer.name
%h5 Posts:
%ul
  - @form.posts.each do |post|
    %li
      = link_to post.id, post
= link_to 'Edit', edit_form_path(@form)
|
= link_to 'Back', forms_path